version: '3.4'

services:
  whatwish:
    image: consul:1.1.0
    hostname: localhost
    ports:
      - "7777:7777"
  redis:
    image: redis:5.0.5
    container_name: redis
    restart: unless-stopped
    hostname: redis
    network_mode: bridge
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379/tcp"